services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: social-network-backend-prod
    restart: unless-stopped
    env_file:
      - .env.production
    ports:
      - "3001:3001"
